### ISSUE TITLE
Spaces in directory names give issues

### ISSUE THREAD

**Issue by krakentoa** [eric-wieser/computercraft-github#18]
Example: https://github.com/mpoegel/ComputerCraft-Scripts

**Comment by eric-wieser** [comment]
Good spot, [this line](https://github.com/eric-wieser/computercraft-github/blob/master/apis/github#L140) needs to url-encode gitpath.

Of course, obviously computercraft does not provide such a url-escape function...

But to fix this issue, I think `gitpath:gsub(' ', '%20')` would suffice?

**Comment by krakentoa** [comment]
Worked after escaping the` %` : `gitpath:gsub(' ', '%%20')`.
Thanks!

**Comment by eric-wieser** [comment]
That doesn't make much sense - why does it need escaping?

**Comment by eric-wieser** [comment]
I've committed without the double %% for now, because I really don't understand why two are needed

**Comment by krakentoa** [comment]
Oh, I got an error of some kind without it. From http://lua-users.org/wiki/PatternsTutorial
> Patterns have a few pre-defined classes, use them as "%x", where "x" is the letter identifying the class:

**Comment by eric-wieser** [comment]
This is not a pattern. It's also not a format string. So % should have no special meaning?

**Comment by eric-wieser** [comment]
Can you tell me the error you get?

**Comment by krakentoa** [comment]
I remember bow it had something to do with an invalid capture. i also found the actual link that gave me the solution:
http://stackoverflow.com/questions/7210581/lua-escaping-literal-inside-string-gsub-and-the-capture-2
