### ISSUE TITLE
Attempt to call nil

### ISSUE THREAD

**Issue by jamjar199** [eric-wieser/computercraft-github#19]
When cloning any repository I always get the error 'github:145: attempt to call nil'
Using both advanced and normal computers
computercraft 1.75

**Comment by eric-wieser** [comment]
As a guess - is http enabled?

Not sure what's going on here - maybe the dofile call is misfiring. What does the top of programs/GitHub show on your install?

**Comment by jamjar199** [comment]
Yeah, http is enabled and I've tested its working.

line 1 is 'local github = dofile("github.rom/apis/github")'

**Comment by eric-wieser** [comment]
If you open the shell, what is the value of `dofile("github.rom/apis/github").repo`? Is it nil? As far as I can tell, that's what's on line 145.

**Comment by jamjar199** [comment]
I got 'function: 6ab0d430' when I printed the value of `dofile("github.rom/apis/github").repo`

line 145 is `local repo = github.repo(user, repo, auth)`

**Comment by eric-wieser** [comment]
Then I don't understand that error message at all. You've just shown that GitHub.repo is not nil elsewhere. Can you add print(github.repo) to that file too?

**Comment by hugeblank** [comment]
So I traced the issue back to the encodeURI function. Are you sure there's a string method called "replace"? I just checked the lua 5.2 documentation and there's no such method.

**Comment by hugeblank** [comment]
made #20 just to fix this :P
