### ISSUE TITLE
OS Safety

### ISSUE THREAD

**Issue by coaster3000** [eric-wieser/computercraft-github#3]
Found the cause of the OS Safety (#2)

When you install this manually by putting it into the rom folder of computercraft..

You must edit the first line in github in the apis folder to 

local JSON = dofile("rom/apis/dkjson")

This fixes that issue..

The reason it works if you manually install on a single computer is because its already calling an apis folder.
As when you install it globalling. The file location is rom/apis/dkjson

It seems the issue also persist in the program itself also when you install globally . Simple fix of editing the same lines on the program itself.

**Comment by aaronmallen** [comment]
this should be resolved with #4

**Comment by aaronmallen** [comment]
@eric-wieser you can close this issue, this was resolved with #4
